// IPC channel names — single source of truth referenced by both main and renderer.

export const IPC = {
  // Forge lifecycle
  forgeStart: 'forge:start',
  forgeStop: 'forge:stop',
  forgeStatus: 'forge:status',
  forgeStatusChanged: 'forge:status-changed',

  // Forge API passthrough
  forgeListModels: 'forge:list-models',
  forgeListSamplers: 'forge:list-samplers',
  forgeListSchedulers: 'forge:list-schedulers',
  forgeRefreshModels: 'forge:refresh-models',
  forgeSetCurrentModel: 'forge:set-current-model',
  forgeTxt2Img: 'forge:txt2img',
  forgeImg2Img: 'forge:img2img',
  forgeInspectVideoSupport: 'forge:inspect-video-support',
  forgeInspectVideoRuntime: 'forge:inspect-video-runtime',
  forgeProgress: 'forge:progress',
  forgeInterrupt: 'forge:interrupt',
  forgeProgressUpdate: 'forge:progress-update',
  forgeImportModels: 'forge:import-models',
  forgeOpenModelsFolder: 'forge:open-models-folder',
  forgeOpenVideoModelFolder: 'forge:open-video-model-folder',
  forgeInterrogate: 'forge:interrogate',
  forgeDisableExtension: 'forge:disable-extension',
  forgeListLoras: 'forge:list-loras',
  forgeRefreshLoras: 'forge:refresh-loras',
  forgeImportLoras: 'forge:import-loras',
  forgeOpenLorasFolder: 'forge:open-loras-folder',
  forgeListVaes: 'forge:list-vaes',
  forgeRefreshVaes: 'forge:refresh-vaes',
  forgeImportVaes: 'forge:import-vaes',
  forgeOpenVaesFolder: 'forge:open-vaes-folder',
  forgeListControlnetModels: 'forge:list-controlnet-models',
  forgeListControlnetModules: 'forge:list-controlnet-modules',
  forgeControlnetDetect: 'forge:controlnet-detect',
  forgeListUpscalers: 'forge:list-upscalers',
  forgeExtraSingleImage: 'forge:extra-single-image',
  framePackInspect: 'framepack:inspect',
  framePackStart: 'framepack:start',
  framePackOpenFolder: 'framepack:open-folder',
  framePackImportLatest: 'framepack:import-latest',
  toolsInspectModel: 'tools:inspect-model',
  toolsPickModelFile: 'tools:pick-model-file',
  toolsScanModelHealth: 'tools:scan-model-health',
  toolsListModelLibrary: 'tools:list-model-library',
  toolsRescanModelLibrary: 'tools:rescan-model-library',
  toolsListDownloadJobs: 'tools:list-download-jobs',
  toolsResumeDownloadJob: 'tools:resume-download-job',
  toolsDiscardDownloadJob: 'tools:discard-download-job',
  toolsOpenDownloadJobFolder: 'tools:open-download-job-folder',
  toolsCheckLibraryIntegrity: 'tools:check-library-integrity',
  toolsDeletePartialFile: 'tools:delete-partial-file',
  toolsHashModelLibraryEntry: 'tools:hash-model-library-entry',
  toolsUpdateModelLibraryEntry: 'tools:update-model-library-entry',
  toolsRefreshModelLibraryCivitai: 'tools:refresh-model-library-civitai',
  toolsRefreshModelLibraryCivitaiBatch: 'tools:refresh-model-library-civitai-batch',
  toolsRunTagger: 'tools:run-tagger',
  toolsRecoverModelLibrary: 'tools:recover-model-library',
  toolsPlanModelAutoOrganize: 'tools:plan-model-auto-organize',
  toolsApplyModelAutoOrganize: 'tools:apply-model-auto-organize',
  toolsConvertModelFormat: 'tools:convert-model-format',
  toolsInspectMergerSupport: 'tools:inspect-merger-support',
  toolsEstimateModelMerger: 'tools:estimate-model-merger',
  toolsRunModelMerger: 'tools:run-model-merger',
  toolsCancelModelMerger: 'tools:cancel-model-merger',
  toolsModelMergerProgress: 'tools:model-merger-progress',
  toolsInspectCharacterCompositeIntegrations: 'tools:inspect-character-composite-integrations',

  // Civitai
  civitaiLookupByModel: 'civitai:lookup-model',
  civitaiHashModel: 'civitai:hash-model',
  civitaiLookupLora: 'civitai:lookup-lora',
  civitaiSearch: 'civitai:search',
  civitaiDownload: 'civitai:download',
  civitaiCancelDownload: 'civitai:cancel-download',
  civitaiDownloadProgress: 'civitai:download-progress',
  civitaiMineCommunity: 'civitai:mine-community',
  civitaiIdentifyFromPng: 'civitai:identify-from-png',
  civitaiListTags: 'civitai:list-tags',
  civitaiCheckUpdates: 'civitai:check-updates',

  // Hugging Face
  huggingFaceSearch: 'huggingface:search',
  huggingFaceDownload: 'huggingface:download',

  // Storage
  storageGetSettings: 'storage:get-settings',
  storageSetSettings: 'storage:set-settings',
  storageListHistory: 'storage:list-history',
  storageAddHistory: 'storage:add-history',
  storageReadHistoryImage: 'storage:read-history-image',
  storageDeleteHistory: 'storage:delete-history',
  storageSetHistoryLabel: 'storage:set-history-label',
  storageSetHistoryTagReview: 'storage:set-history-tag-review',
  storageListPresets: 'storage:list-presets',
  storageSavePreset: 'storage:save-preset',
  storageDeletePreset: 'storage:delete-preset',
  storageGetFavorites: 'storage:get-favorites',
  storageSetFavorites: 'storage:set-favorites',
  storageListQuickPresets: 'storage:list-quick-presets',
  storageSaveQuickPreset: 'storage:save-quick-preset',
  storageDeleteQuickPreset: 'storage:delete-quick-preset',
  storageGetLoraFavorites: 'storage:get-lora-favorites',
  storageSetLoraFavorites: 'storage:set-lora-favorites',
  storageListLoraPromptOverrides: 'storage:list-lora-prompt-overrides',
  storageSaveLoraPromptOverride: 'storage:save-lora-prompt-override',
  storageDeleteLoraPromptOverride: 'storage:delete-lora-prompt-override',
  storageListCheckpointPromptProfiles: 'storage:list-checkpoint-prompt-profiles',
  storageSaveCheckpointPromptProfile: 'storage:save-checkpoint-prompt-profile',
  storageDeleteCheckpointPromptProfile: 'storage:delete-checkpoint-prompt-profile',
  storageRecordLoraUsage: 'storage:record-lora-usage',
  storageListLoraUsage: 'storage:list-lora-usage',
  storageGetHiddenQuickPresets: 'storage:get-hidden-quick-presets',
  storageSetHiddenQuickPresets: 'storage:set-hidden-quick-presets',
  storageListWorkspaces: 'storage:list-workspaces',
  storageSaveWorkspace: 'storage:save-workspace',
  storageLoadWorkspace: 'storage:load-workspace',
  storageDeleteWorkspace: 'storage:delete-workspace',
  storageResolveImageReference: 'storage:resolve-image-reference',
  storageSaveUpscaleComparison: 'storage:save-upscale-comparison',
  storageSaveCharacterComposite: 'storage:save-character-composite',
  storageSaveFabricFeedbackImage: 'storage:save-fabric-feedback-image',
  storageSaveGeneratedVideo: 'storage:save-generated-video',

  // Prompt library
  libraryLoad: 'library:load',
  libraryGetCustom: 'library:get-custom',
  librarySaveCustom: 'library:save-custom',

  // Misc
  appStartupMetrics: 'app:startup-metrics',
  appStartupMetricSamples: 'app:startup-metric-samples',
  openExternal: 'app:open-external',
  showItemInFolder: 'app:show-item-in-folder',
  selectDirectory: 'app:select-directory'
} as const
